[llubi][NFC] Fix build with old GCC (#195327)
Using old GCC (7.5 in this case), we get a compile error about not being
able to deduce the template paramerter:


```
/llvm/llvm/tools/llubi/lib/Interpreter.cpp:770:14: error: no viable constructor or deduction guide for deduction of template arguments of 'std::vector'
  770 |       return std::vector(Vec.begin() + Offset, Vec.begin() + Offset + DstSize);
```

The error was introduced in
https://github.com/llvm/llvm-project/pull/194345.

Just specify the element type.

---------

Signed-off-by: Nick Sarnie <nick.sarnie@intel.com>